# Generated by Django 4.1.2 on 2022-10-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='semesters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='smsapp.semesters'),
        ),
    ]
