# Generated by Django 4.1.2 on 2022-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='section',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
