# Generated by Django 4.1.2 on 2022-10-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_students_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smsapp.courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='semesters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smsapp.semesters'),
        ),
    ]
